# -*- coding: utf-8 -*-
"""IIT PATNA PROJECT 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pi6CQ7yIpG0iewF0BXFGOyMaamCUW0FB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/weather_data.csv')
display(df)

import matplotlib.pyplot as plt
import pandas as pd

# Increase the chunk size for plotting large datasets
plt.rcParams['agg.path.chunksize'] = 10000

df['Date_Time'] = pd.to_datetime(df['Date_Time'])
plt.figure(figsize=(12, 6))
plt.plot(df['Date_Time'], df['Temperature_C'])
plt.xlabel('Date and Time')
plt.ylabel('Temperature (°C)')
plt.title('Temperature Variation Over Time')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Sample data
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y)

# Add axis labels
plt.xlabel('X-axis Label')
plt.ylabel('Y-axis Label')

# Add a title
plt.title('Line Chart with Customizations')

# Add a grid
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(df['Temperature_C'], df['Humidity_pct'], alpha=0.5)
plt.xlabel('Temperature (°C)')
plt.ylabel('Humidity (%)')
plt.title('Temperature vs. Humidity')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Load the dataframe
df=pd.read_csv('/content/drive/MyDrive/weather_data.csv')

plt.figure(figsize=(10, 6))
plt.scatter(df['Wind_Speed_kmh'], df['Temperature_C'], alpha=0.5)
plt.xlabel('Wind Speed (km/h)')
plt.ylabel('Temperature (°C)')
plt.title('Temperature vs. Wind Speed')
plt.grid(True)
plt.show()